### ISSUE TITLE
구글 드라이브 파일이 없습니다.

### ISSUE THREAD

**Issue by jjaegii** [Taehee-K/ASAP#8]
https://drive.google.com/file/d/10ucSBZS_Jg8nvGTIO8uv12JjyZBUPnx6/view?usp=sharing
해당 주소에 npy 파일을 다운받으려고 하는데, 파일이 없다고 합니다.
혹시 다시 올려주실 수 있으실까요?

**Comment by treblenalto** [comment]
해당 파일은 구글드라이브 용량 문제로 현재 삭제되었습니다. 
[9e235b6](https://github.com/Taehee-K/ASAP/commit/9e235b65fed4984e44169a33257e839ab8a4e154)
