### ISSUE TITLE
AI hub 결측 데이터 처리문제

### ISSUE THREAD

**Issue by Rimririn** [Taehee-K/ASAP#9]
안녕하세요. 코드 보면서 따라 해보고 있는데 AI hub에 있는 데이터로 Json 파일이랑 action .json 파일을 만드는데 결측값이 많아서 코드에 오류가 많이 발생합니다. 

혹시 결측값 처리는 어떻게 하셨는지 알 수 있을까요?

**Comment by treblenalto** [comment]
안녕하세요, 
AI Hub 에서 제공하는 데이터 양이 충분하여 기본적으로 결측값이 없는 영상들을 선별해서 진행하였습니다. 
영상 중간에 장애물 등으로 인해 결측값이 생길 경우 평균치를 내어 학습에 사용하였습니다.
